=== SparkleX/help-json2ts/schema/document.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "title": "Document",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "DocEntry": {
            "type": "integer"
        },
        "CardCode": {
            "type": "string",
            "minLength": 1,
            "maxLength": 32,
            "test":1
        },
        "DocTotal": {
            "description": "Document Total",
            "type": "number"
        },
        "Lines": {
            "type": "array",
            "items": {
                "$ref": "documentDetail.json"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "CardCode"
    ]
}

=== SparkleX/help-json2ts/content/order-1.document.json
{
    "$schema": "../schema/document.json",
    "DocEntry": 1,
    "CardCode": "C001",
    "DocTotal": 1.34,
    "Lines" : [
        {
            "LineNum": 0,
            "ItemCode": "I001",
            "LineTotal" : 100.02
        },
        {
            "LineNum": 1,
            "ItemCode": "I002",
            "LineTotal" : 100.01
        }
    ]
}
